// swift-tools-version:5.9
import PackageDescription

// SwiftUI Mac app for Slate. Calls the Rust `slate-core` library through
// the `slate-uniffi` FFI wrapper. Built as a SwiftPM executable while we
// bootstrap; this will graduate to an Xcode project once it needs a
// real .app bundle, entitlements, and code signing.

let package = Package(
    name: "SlateMac",
    platforms: [
        .macOS(.v13),
    ],
    products: [
        .executable(name: "SlateMac", targets: ["SlateMac"]),
    ],
    dependencies: [
        // LaTeXSwiftUI renders LaTeX math expressions to native SwiftUI
        // views via SwiftMath. Used by `MathView` (#220) for the visual
        // representation alongside the MathCAT-generated speech /
        // braille that the AT layer consumes.
        .package(
            url: "https://github.com/colinc86/LaTeXSwiftUI",
            from: "1.5.0"
        ),
    ],
    targets: [
        // System-library target that wraps the C header emitted by
        // uniffi-bindgen. The module name MUST match what the
        // uniffi-generated Swift expects (`slate_uniffiFFI`, mirroring
        // the Rust library name with the `FFI` suffix). The
        // module.modulemap is committed; the header itself is
        // generated by the build script and copied in.
        .systemLibrary(
            name: "slate_uniffiFFI",
            path: "Sources/slate_uniffiFFI"
        ),
        .executableTarget(
            name: "SlateMac",
            dependencies: [
                "slate_uniffiFFI",
                .product(name: "LaTeXSwiftUI", package: "LaTeXSwiftUI"),
            ],
            linkerSettings: [
                .linkedLibrary("slate_uniffi"),
                // -L points at the workspace's Cargo target dir. The
                // build-mac-app.sh script ensures the dylib is built
                // before swift build runs.
                .unsafeFlags([
                    "-L", "../../target/debug",
                ]),
            ]
        ),
        .testTarget(
            name: "SlateMacTests",
            dependencies: ["SlateMac"],
            linkerSettings: [
                // The test binary transitively links slate_uniffi via
                // SlateMac. Reuse the same -L flag so swift test can
                // find the dylib produced by build-mac-app.sh.
                .linkedLibrary("slate_uniffi"),
                .unsafeFlags([
                    "-L", "../../target/debug",
                ]),
            ]
        ),
    ]
)
