// Copyright (C) 2026 Cory Joseph
// SPDX-License-Identifier: AGPL-3.0-or-later

import XCTest

@testable import SlateMac

/// §W-D parity census (W0.5-3, #719): the mac half of the canonical
/// a11y-event corpus check. Constructs every representative event from
/// `slate_core::a11y::corpus()` in the SAME order, renders each through
/// the FFI (`a11yRender` — the exact path `postAccessibilityAnnouncement(
/// _ event:)` posts through), and asserts (priority, text) against the
/// committed artifact `tests/fixtures/a11y/corpus.json`. Each entry's
/// `event` field (core's Debug identity, via `a11yEventIdentity`) is
/// asserted too, so the mirror must construct the SAME semantic event —
/// not merely one that happens to render identical text. The Windows
/// census (`A11yCorpusCensus`, #1114) consumes the same file, which is
/// what makes the corpus the cross-platform anchor: if this test and its
/// Windows twin are green, both hosts speak identical announcements for
/// identical events. The two mirrors are maintained in lockstep.
///
/// Corpus changes are DELIBERATE: regenerate the artifact core-side
/// (`SLATE_REGENERATE_FIXTURES=1 cargo test -p slate-core a11y` — that
/// run fails by design after rewriting; re-run clean to prove the pin),
/// update the mirrored construction below, and review the diff as a
/// §W-D delta.
final class A11yCorpusCensusTests: XCTestCase {

    private struct CorpusEntry: Decodable {
        let event: String
        let priority: String
        let text: String
    }

    /// Repo-root fixture path derived from this file's location — the first
    /// delete strips the filename, then four directory hops
    /// (SlateMacTests → Tests → slate-mac → apps) reach the repo root.
    private static var corpusURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // strips the filename → SlateMacTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // slate-mac
            .deletingLastPathComponent()  // apps
            .deletingLastPathComponent()  // repo root
            .appendingPathComponent("tests/fixtures/a11y/corpus.json")
    }

    /// The Swift mirror of `slate_core::a11y::corpus()` — same events,
    /// same sample values, same order.
    private static var corpus: [A11yEvent] {
        [
            .filesRegionFocused,
            .leafPanelShown(title: "Outline"),
            .editorPaneFocused(ordinal: 2, total: 3, title: "notes.md", prefix: ""),
            .tabFocused(prefix: "Now", filename: "notes.md", index: 1, count: 4),
            .tabClosed(closedTitle: "draft.md", successor: "notes.md"),
            .tabClosed(closedTitle: "draft.md", successor: nil),
            .noSplitPanesToResize,
            .paneResized(percent: 60),
            .graphOpensSinglePane,
            .rightPaneShown,
            .rightPaneHidden,
            .historyPanelShown,
            .reopenTargetMissing(filename: "gone.md"),
            .reopenedFile(filename: "notes.md"),
            .reopenedNamed(name: "Open tasks"),
            .reopenedGraph,
            .vaultOpened(vaultTitle: "Garden", sidebarNotice: ""),
            .removedRecentVault(displayName: "Garden"),
            .welcomeShown(recentVaultCount: 0),
            .welcomeShown(recentVaultCount: 1),
            .welcomeShown(recentVaultCount: 2),
            .commandPaletteNeedsVault,
            .searchNeedsVault,
            .searchResultsSummary(count: 0),
            .searchResultsSummary(count: 1),
            .searchResultsSummary(count: 7),
            .searchFailed(message: "the index is unavailable"),
            .searchResultOpened(filename: "notes.md", line: 12, snippet: "the quick brown fox"),
            .externalLinkUnsupported(target: "ftp://example.com"),
            .externalLinkOpened,
            .externalLinkFailed(target: "https://example.com"),
            .linkUnresolved(target: "Missing Note"),
            .helpOpened,
            .helpFailed,
            .internalNavigated(kind: "Opened", filename: "notes.md"),
            .citationNotLoaded,
            .noResolvedEmbedAtCursor,
            .noEmbedAtCursor,
            .headingNotFound,
            .headingScrollFailed(heading: "Roadmap"),
            .scrolledToHeading(heading: "Roadmap"),
            .scrolledToLine(filename: "notes.md", line: 40),
            .openedAtLine(filename: "notes.md", line: 40),
            .openedFile(filename: "notes.md"),
            .showingNote(displayName: "notes"),
            .taskToggleUnsaved(filename: "notes.md"),
            .taskToggleConflict(filename: "notes.md"),
            .tasksReviewShown(filterName: "Open tasks"),
            .tasksFilterSet(filterName: "All tasks"),
            .noteSaved(filename: "notes.md"),
            .saveConflict(filename: "notes.md"),
            .restoredVersionFrom(formattedDate: "July 19, 2026 at 9:41 AM"),
            .restoredFile(filename: "notes.md"),
            .restoredFileAs(sourceName: "notes.md", filename: "notes-restored.md"),
            .printNeedsNote,
            .printDialogOpened(name: "notes.md"),
            .batchCheckStarted(formattedCount: "1,024", actionName: "Move"),
            .selectionCopied,
            .sidebarSettingsStillDefaults(detail: "the file is malformed."),
            .sidebarSettingsReloadedStaleRefs,
            .sidebarSettingsReloaded,
            .vaultClosed,
            .vaultClosedAllSaved,
            .vaultClosedChangesDiscarded,
            .propertiesUpdated,
            .propertyChanged(key: "tags", deleted: false),
            .propertyChanged(key: "tags", deleted: true),
            .propertyEditConflict(filename: "notes.md"),
            .propertiesSourceRejected(reason: "the YAML does not parse"),
            .propertyEditFailed(detail: "io error"),
            .propertiesReloaded,
            .propertiesReloadedBodyChanged,
            .noteChangedAgain(detail: nil),
            .noteChangedAgain(detail: "The note changed while saving."),
            .propertiesReloadFailed(reason: "io error"),
            .propertyRetainedCopied,
            .propertyRecoveryUnverified(displayName: "notes"),
            .propertyRetainedDiscarded,
            .propertyRetainedReapplyFailed(detail: nil),
            .propertyReloadStillFailed(reason: "io error"),
            .propertyLoadCurrentFailed(reason: "io error"),
            .addPropertySheetShown,
            .sourceChangesDiscarded,
            .bulkRenameSheetShown,
            .renameReloadFailed(detail: nil),
            .renameFailed(detail: "io error"),
            .renameSummary(applied: true, renamed: 3, skipped: 1, failed: 0),
            .renameSummary(applied: false, renamed: 1, skipped: 0, failed: 0),
            .renameSummary(applied: false, renamed: 3, skipped: 2, failed: 0),
            .duplicateFilesOnly,
            .mathSpeechStyle(name: "ClearSpeak"),
            .mathVerbosity(name: "Verbose"),
            .mathBrailleCode(name: "Nemeth"),
            .codePreambleVerbosity(name: "Concise"),
            .editorTextSize(percent: 110),
            .spellCheckToggled(enabled: true),
            .spellCheckToggled(enabled: false),
            .citationStyleChanged(title: "APA"),
            .citationsCount(count: 1),
            .citationsCount(count: 3),
            .outlineCount(count: 1),
            .outlineCount(count: 5),
            .fileListCount(count: 1),
            .fileListCount(count: 12),
            .itemsSelected(count: 4),
            .itemsSelected(count: 1),
            .noItemsSelected,
            .treeFolderSelected(name: "Archive"),
            .rowSelected(name: "notes"),
            .switcherRecentCount(count: 2),
            .switcherRecentCount(count: 1),
            .switcherRecentCount(count: 0),
            .switcherNoMatches(query: "zzz"),
            .switcherMatchCount(count: 2, query: "foo"),
            .switcherMatchCount(count: 1, query: "foo"),
            .paletteCommandSelected(label: "Save", disabledReason: nil),
            .paletteCommandSelected(
                label: "Save",
                disabledReason: "A structural operation is in progress."
            ),
            .paletteFilterCount(count: 0, query: "zzz"),
            .paletteFilterCount(count: 1, query: "save"),
            .paletteFilterCount(count: 4, query: "e"),
            .paletteCommandFailed(label: "Save", detail: "disk full"),
            .paletteCommandFailed(label: "Save", detail: nil),
            .paletteCommandNotFound(id: "slate.nope"),
            .paletteCommandUnavailable(reason: "A structural operation is in progress."),
            .recentSearchFocused(query: "fox"),
            .quickSwitcherCount(count: 2, query: nil),
            .quickSwitcherCount(count: 1, query: nil),
            .quickSwitcherCount(count: 2, query: "foo"),
            .quickSwitcherCount(count: 1, query: "foo"),
            .quickSwitcherCount(count: 0, query: "zzz"),
            .baseViewMode(mode: "cards"),
            .baseViewSwitcher(viewCount: 1),
            .baseViewSwitcher(viewCount: 2),
            .basesNewQueryBuilder,
            .basesEditingFilters(viewName: "Table"),
            .basesFiltersOpenFailed(detail: "io error"),
            .basesPreviewFailed(detail: "bad expression"),
            .basesBuilderSaved,
            .basesViewSaveFailed(detail: "io error"),
            .basesSavedQueryNameNeeded,
            .basesSavedQueryCreated(name: "Open tasks"),
            .basesSavedQueryCreateFailed(detail: "io error"),
            .basesSavedQueryUpdated(name: "Open tasks"),
            .basesSavedQueryUpdateFailed(detail: "io error"),
            .basesViewSelected(name: "Cards"),
            .basesSortSaveFailed(detail: "io error"),
            .baseRefreshed,
            .baseWhereAmI(base: "Reading", view: nil, quickFilter: nil),
            .baseWhereAmI(base: "Reading", view: "Table", quickFilter: nil),
            .baseWhereAmI(base: "Reading", view: "Table", quickFilter: "CAFE"),
            .baseResultsPopover(audioSummary: "12 results.", whereAmI: nil),
            .baseResultsPopover(
                audioSummary: "12 results.",
                whereAmI: "Base: Reading, quick filter: CAFE"),
            .baseQuickFilterResult(shown: 0, total: 0),
            .baseQuickFilterResult(shown: 1, total: 1),
            .baseQuickFilterResult(shown: 1, total: 2),
            .baseRowReorderRefused(label: "Sort 1"),
            .baseRowReorderAtBoundary(label: "Sort 1", atFirst: true),
            .baseRowReorderAtBoundary(label: "Sort 2", atFirst: false),
            .baseRowReorderMoved(label: "Sort 1", movedUp: false, position: 2, count: 3),
            .baseRowReorderMoved(label: "Status column", movedUp: true, position: 1, count: 3),
            .baseQueryPreviewIdle,
            .baseQueryPreviewLoading,
            .baseQueryPreviewReady(audioSummary: "12 results.", firstResult: nil),
            .baseQueryPreviewReady(audioSummary: "12 results", firstResult: "Alpha"),
            .baseQueryPreviewReady(audioSummary: "12 results.", firstResult: "Alpha"),
            .baseQueryPreviewFailed(detail: "invalid expression"),
            .baseSortedByColumn(column: "Status", ascending: true),
            .baseSortedByColumn(column: "Status", ascending: false),
            .baseSortSavedToView(column: "Status", ascending: true),
            .baseSortSavedToView(column: "Status", ascending: false),
            .basesSavedQueryReferenceMissing(reference: "Open tasks"),
            .basesSavedQueryMissing,
            .basesQueriesRefreshFailed(detail: "io error"),
            .basesSavedQueryEditing(name: "Open tasks"),
            .basesSavedQueryEditFailed(detail: "io error"),
            .basesSavedQueryRenameNameNeeded,
            .basesSavedQueryRenamed(name: "Open tasks"),
            .basesSavedQueryRenameFailed(detail: "io error"),
            .basesSavedQueryDeleted,
            .basesSavedQueryDeleteFailed(detail: "io error"),
            .basesSavedQueryExportPathNeeded,
            .basesSavedQueryExported(name: "Open tasks.base"),
            .basesSavedQueryExportFailed(detail: "io error"),
            .basesPathOutsideVault,
            .basesDashboardNameNeeded,
            .basesDashboardSaved(name: "Reading"),
            .basesDashboardSaveFailed(detail: "io error"),
            .basesDashboardUpdated(name: "Reading"),
            .basesDashboardUpdateFailed(detail: "io error"),
            .basesDashboardSectionStale,
            .basesDashboardSectionRemoveFailed(detail: "io error"),
            .basesDashboardSectionReplaceFailed(detail: "io error"),
            .basesDashboardDeleted,
            .basesDashboardDeleteFailed(detail: "io error"),
            .basesDashboardEditFailed(detail: "io error"),
            .basesDashboardMissing,
            .basesDockUpdatedForNote,
            .basesLinkCopied(name: "Reading"),
            .basesBacklinksFor(name: "Reading"),
            .basesViewCopyNoActiveBase,
            .basesViewCopiedAsMarkdown,
            .basesViewCopyFailed(detail: "io error"),
            .basesRowSelectionNeeded,
            .basesNoEditableProperty,
            .basesCellReadOnly(fileMetadata: true),
            .basesCellReadOnly(fileMetadata: false),
            .basesCellSaved(column: "Status", value: "Done"),
            .basesCellCleared(column: "Status"),
            .basesCellRowNoLongerMatches,
            .basesCellEditFailed(detail: "io error"),
            .basesCellEditCanceled,
            .basesViewExported,
            .basesViewExportFailed(detail: "io error"),
            .basesDataviewConverted,
            .basesDataviewConversionSaveFailed(detail: "io error"),
            .basesQuickFilterChoiceCanceled(verb: "Export"),
            .basesCellMustBeFiniteNumber,
            .basesCellMustBeWholeNumber,
            .basesCellMustBeFiniteDecimal,
            .basesCellMustBeBoolean,
            .basesCellMustBeDate,
            .basesRefreshUpdated(audioSummary: "1 note."),
            .dataviewConversionFailed(detail: "unsupported query"),
            .citationInsertUnavailable,
            .citationWalkThrough,
            .codeCopied,
            .readingNavNoTarget(target: .heading, forward: true),
            .readingNavNoTarget(target: .headingLevel(level: 2), forward: false),
            .readingNavNoTarget(target: .link, forward: true),
            .readingNavNoTarget(target: .list, forward: false),
            .readingNavNoTarget(target: .table, forward: true),
            .readingNavNoTarget(target: .embed, forward: false),
            .readingNavNoTarget(target: .codeBlock, forward: true),
            .readingNavLanded(target: .headingLevel(level: 2), text: "Lists and tasks"),
            .readingNavLanded(target: .link, text: "Target Note"),
            .readingNavLanded(target: .list, text: "first bullet"),
            .readingNavLanded(target: .table, text: "column a"),
            .readingNavLanded(target: .embed, text: "Embedded note Target Note"),
            .readingNavLanded(target: .codeBlock, text: "fn spoken_interior() -> usize { 42 }"),
            .readingNavNoTarget(target: .math, forward: true),
            .readingNavLanded(
                target: .math,
                text: "x equals negative b plus or minus the square root of b squared minus 4 a c, over 2 a"),
            .readingNavNoTarget(target: .diagram, forward: true),
            .readingNavLanded(target: .diagram, text: "Flowchart with 3 steps"),
            .readingNavLanded(target: .embed, text: ""),
            .gridSorted(column: "Status", ascending: true),
            .gridSorted(column: "Due", ascending: false),
            .gridRowMoved(
                description: "Ship the plan. Status: Open. Due: Friday",
                focusedCell: "Status: Open"),
            .gridRowMoved(description: "Ship the plan", focusedCell: "Status: Open"),
            .gridRowMoved(description: "Done reviewing.", focusedCell: "Status: Open"),
            .gridRowMoved(description: "Substatus: Opening", focusedCell: "Status: Open"),
            .gridRowMoved(
                description: "Status: Open Questions remain",
                focusedCell: "Status: Open"),
            .gridCellMoved(column: "Status", value: "Open"),
            .gridGroup(label: "Open", rowCount: 1, summary: nil),
            .gridGroup(label: "Done", rowCount: 12, summary: "Count: 12"),
            .templatePickerOpened(count: 0),
            .templatePickerOpened(count: 1),
            .templatePickerOpened(count: 7),
            .templateNoteCreated(name: "Meeting 2026-08-20.md", template: "Meeting"),
            .hostComposed(text: "Composed by a host engine.", priority: .high),
            // --- Canvas (W6-1 0a, #745) ---
            .canvasMovedTo(verbosity: .terse, kindLabel: "text", title: "Research", ordinalN: 2, totalM: 5, container: "Q3", connectionCount: 3, colorName: "red", marked: true),
            .canvasMovedTo(verbosity: .standard, kindLabel: "text", title: "Research", ordinalN: 2, totalM: 5, container: "Q3", connectionCount: 3, colorName: "red", marked: true),
            .canvasMovedTo(verbosity: .verbose, kindLabel: "text", title: "Research", ordinalN: 2, totalM: 5, container: "Q3", connectionCount: 3, colorName: "red", marked: true),
            .canvasMovedTo(verbosity: .standard, kindLabel: "group", title: "Q3", ordinalN: 1, totalM: 3, container: nil, connectionCount: 0, colorName: nil, marked: false),
            .canvasMovedTo(verbosity: .verbose, kindLabel: "file", title: "Notes.md", ordinalN: 1, totalM: 1, container: nil, connectionCount: 1, colorName: nil, marked: false),
            .canvasGroupEntered(label: "Q3", count: 4),
            .canvasGroupEntered(label: "Solo", count: 1),
            .canvasGroupLeft(label: "Q3"),
            .canvasConnectionTraversed(direction: .outgoing, kindLabel: "text", title: "Ideas", label: "supports"),
            .canvasConnectionTraversed(direction: .incoming, kindLabel: "text", title: "Research", label: nil),
            .canvasConnectionTraversed(direction: .undirected, kindLabel: "group", title: "Q3", label: nil),
            .canvasConnectionTraversed(direction: .bidirectional, kindLabel: "link", title: "example.com", label: nil),
            .canvasTracePathEnd(titles: ["Research", "Ideas", "Draft"]),
            .canvasMoveRelative(descs: [], overlap: nil),
            .canvasMoveRelative(descs: [.below(anchorTitle: "Research")], overlap: nil),
            .canvasMoveRelative(descs: [.below(anchorTitle: "Research"), .rightOf(anchorTitle: "Ideas")], overlap: .onset),
            .canvasMoveRelative(descs: [.above(anchorTitle: "Ideas")], overlap: .cleared),
            .canvasResizeGeometry(preset: nil, width: 320, height: 200, overlap: nil),
            .canvasResizeGeometry(preset: .defaultSize, width: 260, height: 140, overlap: nil),
            .canvasResizeGeometry(preset: .fitToContent, width: 260, height: 88, overlap: .onset),
            .canvasResizeClamped,
            .canvasModeEntered(mode: .move, object: .card(title: "Research")),
            .canvasModeEntered(mode: .move, object: .cards(count: 3)),
            .canvasModeEntered(mode: .resize, object: .card(title: "Research")),
            .canvasModeEntered(mode: .connect, object: .card(title: "Research")),
            .canvasModeRejected(activeMode: .move),
            .canvasModeCommitted(verb: .move, object: .card(title: "Research")),
            .canvasModeCommitted(verb: .move, object: .cards(count: 3)),
            .canvasModeCommitted(verb: .resize, object: .card(title: "Research")),
            .canvasModeEndedWithoutEffect(mode: .move),
            .canvasModeEndedWithoutEffect(mode: .resize),
            .canvasModeEndedWithoutEffect(mode: .connect),
            .canvasModeCancelled(mode: .move, restoration: .unstated),
            .canvasModeCancelled(mode: .move, restoration: .cardsReturned(count: 1)),
            .canvasModeCancelled(mode: .move, restoration: .cardsReturned(count: 3)),
            .canvasModeCancelled(mode: .resize, restoration: .unstated),
            .canvasModeCancelled(mode: .resize, restoration: .sizeRestored),
            .canvasModeCancelled(mode: .connect, restoration: .unstated),
            .canvasModeCancelled(mode: .connect, restoration: .backAt(title: "Research")),
            .canvasCreated(kindLabel: "text", title: "New idea", relative: .below(anchorTitle: "Research")),
            .canvasCreated(kindLabel: "group", title: "Q3", relative: .rightOf(anchorTitle: "Research")),
            .canvasCreated(kindLabel: "file", title: "Notes.md", relative: .above(anchorTitle: "Research")),
            .canvasCreated(kindLabel: "link", title: "example.com", relative: .leftOf(anchorTitle: "Research")),
            .canvasCreated(kindLabel: "text", title: "Untitled", relative: .atOrigin),
            .canvasFileCreated(name: "Roadmap"),
            .canvasConnectedCardCreated(relative: .below(anchorTitle: "Research"), originTitle: "Research"),
            .canvasConnected(fromTitle: "Research", toTitle: "Ideas", label: "supports"),
            .canvasConnected(fromTitle: "Research", toTitle: "Ideas", label: nil),
            .canvasConnectionUpdated(label: "supports"),
            .canvasConnectionUpdated(label: nil),
            .canvasMovedIntoGroup(label: "Q3"),
            .canvasRemovedFromGroup(label: "Q3"),
            .canvasColorSet(title: "Research", colorName: "red"),
            .canvasColorSet(title: "Research", colorName: nil),
            .canvasRenamedGroup(label: "Q3"),
            .canvasCardUpdated(title: "Research"),
            .canvasCardRetargeted(title: "Research", path: "notes/research.md"),
            .canvasCardPlaced(verb: .moved, title: "Research", relative: .below(anchorTitle: "Ideas")),
            .canvasCardPlaced(verb: .duplicated, title: "Research", relative: .rightOf(anchorTitle: "Research")),
            .canvasCardAligned(title: "Research", targetTitle: "Ideas"),
            .canvasConvertedToNote(path: "notes/research.md"),
            .canvasDeleted(target: .card(kindLabel: "text", title: "Research"), verbosity: .standard, undoChord: "⌘Z"),
            .canvasDeleted(target: .card(kindLabel: "text", title: "Research"), verbosity: .terse, undoChord: "⌘Z"),
            .canvasDeleted(target: .group(label: "Q3"), verbosity: .standard, undoChord: "⌘Z"),
            .canvasDeleted(target: .cards(count: 3), verbosity: .standard, undoChord: "Ctrl+Z"),
            .canvasDeleted(target: .cards(count: 1), verbosity: .verbose, undoChord: "⌘Z"),
            .canvasDeleted(target: .connection(direction: .outgoing, otherTitle: "Ideas", label: "supports"), verbosity: .standard, undoChord: "⌘Z"),
            .canvasDeleted(target: .connection(direction: .incoming, otherTitle: "Research", label: nil), verbosity: .terse, undoChord: "⌘Z"),
            .canvasDeleted(target: .connection(direction: .undirected, otherTitle: "Q3", label: nil), verbosity: .standard, undoChord: "⌘Z"),
            .canvasBulkMoved(count: 3, relative: .below(anchorTitle: "Research")),
            .canvasBulkColorSet(count: 3, colorName: "cyan"),
            .canvasBulkColorSet(count: 1, colorName: nil),
            .canvasGrouped(count: 3, label: "Q3"),
            .canvasBulkDuplicated(count: 2),
            .canvasMarkToggled(marked: true, title: "Research", count: 2),
            .canvasMarkToggled(marked: false, title: "Research", count: 1),
            .canvasMarksCleared(count: 0),
            .canvasMarksCleared(count: 3),
            .canvasFilterCount(matched: 3),
            .canvasFilterCount(matched: 1),
            .canvasFilterCleared(total: 40),
            .canvasFilterCleared(total: 1),
            .canvasZoom(context: nil, percent: 100),
            .canvasZoom(context: .fitCanvas, percent: 80),
            .canvasZoom(context: .zoomedToSelection, percent: 150),
            .canvasFollowSelectionToggled(following: true),
            .canvasFollowSelectionToggled(following: false),
            .canvasSurfaceShown(surface: .outline),
            .canvasSurfaceShown(surface: .table),
            .canvasSurfaceShown(surface: .visual),
            .canvasHistoryApplied(verb: .undo, name: "move \"Research\""),
            .canvasHistoryApplied(verb: .redo, name: "move \"Research\""),
            .canvasUndoMenuTitle(verb: .undo, name: "delete \"My Card\""),
            .canvasUndoMenuTitle(verb: .redo, name: ""),
            .canvasStatus(note: .nothingSelected),
            .canvasStatus(note: .noMarks),
            .canvasStatus(note: .notAGroup),
            .canvasStatus(note: .notATextCard),
            .canvasStatus(note: .notAFileCard),
            .canvasStatus(note: .noGroups),
            .canvasStatus(note: .noNotesInVault),
            .canvasStatus(note: .noMediaInVault),
            .canvasStatus(note: .noFilesToPointAt),
            .canvasStatus(note: .onlyTextCardsConvert),
            .canvasStatus(note: .noConnections),
            .canvasStatus(note: .pickOutsideMovingSet),
            .canvasStatus(note: .pickDifferentTarget),
            .canvasStatus(note: .noChanges),
            .canvasStatus(note: .notReadable),
            .canvasStatus(note: .empty),
            .canvasStatus(note: .endOfCanvas),
            .canvasStatus(note: .startOfCanvas),
            .canvasStatus(note: .atCanvasLevel),
            .canvasStatus(note: .noCardsMatchFilter),
            .canvasStatus(note: .nothingToUndo),
            .canvasStatus(note: .nothingToRedo),
            .canvasStatus(note: .groupIsEmpty(label: "Q3")),
            .canvasStatus(note: .noOutgoingPath(title: "Research")),
            .canvasStatus(note: .notInAGroup(title: "Research")),
            .canvasStatus(note: .noConnection(forward: true, ordinal: nil)),
            .canvasStatus(note: .noConnection(forward: true, ordinal: 2)),
            .canvasStatus(note: .noConnection(forward: false, ordinal: nil)),
            .canvasBlocked(reason: .modeBusy),
            .canvasBlocked(reason: .undoBlocked),
            .canvasBlocked(reason: .redoBlocked),
            .canvasBlocked(reason: .linkOpenFailed),
            .canvasBlocked(reason: .alignWouldOverlap),
            .canvasBlocked(reason: .notAUrl),
            .canvasBlocked(reason: .cardTextUnreadable),
            .canvasBlocked(reason: .notePathMustEndInMd),
            .canvasBlocked(reason: .noFreeSpaceInGroup(label: "Q3")),
            .canvasBlocked(reason: .notePathExists(path: "notes/research.md", onDisk: false)),
            .canvasBlocked(reason: .notePathExists(path: "notes/research.md", onDisk: true)),
            .canvasBlocked(reason: .noteReadFailed(message: "The card text is unavailable.")),
            .canvasBlocked(reason: .noteCreateFailed(path: "notes/research.md", message: "io error")),
            .canvasBlocked(reason: .noteRetargetFailed(path: "notes/research.md", message: "io error")),
            .canvasBlocked(reason: .headingNotFound(heading: "Roadmap", filename: "notes.md")),
            .canvasBlocked(reason: .reopenFailed(message: "The file moved.")),
            .canvasActionFailed(action: .newCard, detail: "the file is read-only"),
            .canvasActionFailed(action: .newGroup, detail: "the file is read-only"),
            .canvasActionFailed(action: .newCanvas, detail: "the file is read-only"),
            .canvasActionFailed(action: .moveIntoGroup, detail: "the file is read-only"),
            .canvasActionFailed(action: .placement, detail: "the file is read-only"),
            .canvasActionFailed(action: .align, detail: "the file is read-only"),
            .canvasActionFailed(action: .create, detail: "the file is read-only"),
            .canvasActionFailed(action: .removeFromGroup, detail: "the file is read-only"),
            .canvasActionFailed(action: .duplicate, detail: "the file is read-only"),
            .canvasActionFailed(action: .createConnectedCard, detail: "the file is read-only"),
            .canvasActionFailed(action: .canvasAction, detail: "the file is read-only"),
            .canvasActionFailed(action: .whereAmI, detail: "the file is read-only"),
            .canvasSaveConflict,
            .canvasFileNotFound(target: "media/diagram.png"),
            .canvasOpened(title: "Notes.md", target: .defaultApp),
            .canvasOpened(title: "example.com", target: .browser),
            .canvasMutationRefused(reason: .opening),
            .canvasMutationRefused(reason: .reopening),
            .canvasMutationRefused(reason: .retargetFailed),
            .canvasMutationRefused(reason: .unavailable),
            .canvasMutationRefused(reason: .readOnly),
            .canvasMutationRefused(reason: .cardEditorUnavailable),
            .canvasLoadedDegraded(skipped: 3),
            .canvasLoadedDegraded(skipped: 1),
            .canvasEmptyOnboarding(newCardChord: "Option Command N", paletteChord: "Command Shift P"),
            .canvasWhereAmI(kindLabel: "text", title: "Research", groupPath: ["Quarter", "Q3"], ordinalN: 2, totalM: 5, connectionCount: 3, inCount: 1, outCount: 2, colorName: "red", marked: true, mode: .move, filter: .active(matched: 3, total: 40)),
            .canvasWhereAmI(kindLabel: "text", title: "Loose", groupPath: [], ordinalN: 1, totalM: 1, connectionCount: 1, inCount: 1, outCount: 0, colorName: nil, marked: false, mode: nil, filter: .inactive),
        ]
    }

    func testEveryCorpusEventRendersTheCommittedTextAndPriority() throws {
        let data = try Data(contentsOf: Self.corpusURL)
        let entries = try JSONDecoder().decode([CorpusEntry].self, from: data)
        let corpus = Self.corpus

        XCTAssertEqual(
            corpus.count, entries.count,
            "Swift corpus mirror and the committed artifact must stay in lockstep"
        )

        for (index, (event, entry)) in zip(corpus, entries).enumerated() {
            XCTAssertEqual(
                a11yEventIdentity(event: event), entry.event,
                "event identity mismatch at corpus[\(index)] — the mirror "
                    + "constructed a different variant or parameters than the artifact pins"
            )
            let rendered = a11yRender(event: event)
            XCTAssertEqual(
                rendered.text, entry.text,
                "text mismatch at corpus[\(index)] (\(entry.event))"
            )
            let priority = rendered.priority == .high ? "high" : "medium"
            XCTAssertEqual(
                priority, entry.priority,
                "priority mismatch at corpus[\(index)] (\(entry.event))"
            )
        }
    }

    /// The poster path itself: posting an event routes core's rendered
    /// (text, priority) into the platform primitive verbatim.
    func testEventPosterUsesTheCanonicalRendering() {
        final class RecordingPoster: AnnouncementPosting {
            var posted: [(String, AnnouncementPriority)] = []
            func post(_ message: String, priority: AnnouncementPriority) {
                posted.append((message, priority))
            }
        }
        let poster = RecordingPoster()
        poster.post(A11yEvent.noteSaved(filename: "notes.md"))
        poster.post(A11yEvent.commandPaletteNeedsVault)

        XCTAssertEqual(poster.posted.count, 2)
        XCTAssertEqual(poster.posted[0].0, "Saved notes.md.")
        XCTAssertEqual(poster.posted[0].1, .medium)
        XCTAssertEqual(poster.posted[1].0, "Open a vault to use the command palette.")
        XCTAssertEqual(poster.posted[1].1, .high)
    }
}
