// swift-tools-version:5.9
import PackageDescription

// Smoke-test SwiftUI app for YANA on macOS.
//
// Calls the Rust `yana-core` library through the `yana-uniffi`
// FFI wrapper. Builds the bindings into a SwiftPM executable.
//
// The real Mac app will eventually be an Xcode project with a
// proper .app bundle, code signing, and sandbox entitlements. For
// now this validates that the Rust → uniffi → SwiftUI toolchain
// works end-to-end on Apple Silicon.

let package = Package(
    name: "YanaMac",
    platforms: [
        .macOS(.v13),
    ],
    products: [
        .executable(name: "YanaMac", targets: ["YanaMac"]),
    ],
    targets: [
        // System-library target that wraps the C header emitted by
        // uniffi-bindgen. The module name MUST match what the
        // uniffi-generated Swift expects (`yana_uniffiFFI`, mirroring
        // the Rust library name with the `FFI` suffix). The
        // module.modulemap is committed; the header itself is
        // generated by the build script and copied in.
        .systemLibrary(
            name: "yana_uniffiFFI",
            path: "Sources/yana_uniffiFFI"
        ),
        .executableTarget(
            name: "YanaMac",
            dependencies: ["yana_uniffiFFI"],
            linkerSettings: [
                .linkedLibrary("yana_uniffi"),
                // -L points at the workspace's Cargo target dir. The
                // build-mac-app.sh script ensures the dylib is built
                // before swift build runs.
                .unsafeFlags([
                    "-L", "../../target/debug",
                ]),
            ]
        ),
    ]
)
