// swift-tools-version:5.9
import PackageDescription

// SwiftUI Mac app for YANA. Calls the Rust `yana-core` library through
// the `yana-uniffi` FFI wrapper. Built as a SwiftPM executable while we
// bootstrap; this will graduate to an Xcode project once it needs a
// real .app bundle, entitlements, and code signing.

let package = Package(
    name: "YanaMac",
    platforms: [
        .macOS(.v13),
    ],
    products: [
        .executable(name: "YanaMac", targets: ["YanaMac"]),
    ],
    targets: [
        // System-library target that wraps the C header emitted by
        // uniffi-bindgen. The module name MUST match what the
        // uniffi-generated Swift expects (`yana_uniffiFFI`, mirroring
        // the Rust library name with the `FFI` suffix). The
        // module.modulemap is committed; the header itself is
        // generated by the build script and copied in.
        .systemLibrary(
            name: "yana_uniffiFFI",
            path: "Sources/yana_uniffiFFI"
        ),
        .executableTarget(
            name: "YanaMac",
            dependencies: ["yana_uniffiFFI"],
            linkerSettings: [
                .linkedLibrary("yana_uniffi"),
                // -L points at the workspace's Cargo target dir. The
                // build-mac-app.sh script ensures the dylib is built
                // before swift build runs.
                .unsafeFlags([
                    "-L", "../../target/debug",
                ]),
            ]
        ),
        .testTarget(
            name: "YanaMacTests",
            dependencies: ["YanaMac"],
            linkerSettings: [
                // The test binary transitively links yana_uniffi via
                // YanaMac. Reuse the same -L flag so swift test can
                // find the dylib produced by build-mac-app.sh.
                .linkedLibrary("yana_uniffi"),
                .unsafeFlags([
                    "-L", "../../target/debug",
                ]),
            ]
        ),
    ]
)
