#!/usr/bin/env python3
# Copyright (C) 2026 Cory Joseph
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate W7's whole-vocabulary trigger and residue ledgers.

The inventory comes from A11yTriggerInventory: Roslyn-bound Windows
constructions and the documented SwiftSource lexical boundary. Generation
and the census share that source authority, rather than maintaining a
second regex interpretation of C#. Bindings must already be regenerated.

    python scripts/a11y_trigger_ledger.py --write
    python scripts/a11y_trigger_ledger.py --check

Both commands obtain a fresh inventory through the test project. --inventory
is an explicit development shortcut for inspecting an already exported file.
The ordinary census independently reads the current trees and committed table.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import tempfile

REPO = Path(__file__).resolve().parent.parent
CONFIG = REPO / "docs/plans/18_windows_port/a11y_trigger_designations.json"
DOCUMENT = REPO / "docs/plans/38_notification_dispatcher_contracts.md"
BEGIN = "<!-- a11y-trigger-ledger:start -->"
END = "<!-- a11y-trigger-ledger:end -->"
CORPUS_FACT = "Censuses/A11yCorpusCensus.cs#EveryCorpusEventRendersTheCommittedIdentityTextAndPriority"
DISPATCH_FACT = "AccessibilityNotificationDispatcherTests.cs#EveryCorpusEventReachesTheNativeBoundaryWithItsGoldenTextAndPriority"
FAMILIES = {
    "Canvas": ("34_canvas_contracts.md", "CanvasTriggerParityCensus.cs#TheLedgerHasARowForEveryStructuralKeyAndNoOther"),
    "Graph": ("35_graph_contracts.md", "GraphTriggerParityCensus.cs#TheLedgerHasARowForEveryStructuralKeyWithItsRoleAndNoOther"),
}


def inventory() -> dict:
    with tempfile.TemporaryDirectory(prefix="slate-a11y-ledger-") as directory:
        output = Path(directory) / "inventory.json"
        env = dict(os.environ, SLATE_A11Y_INVENTORY_PATH=str(output))
        command = ["dotnet", "test", str(REPO / "apps/slate-windows/tests/SlateWindows.Tests/SlateWindows.Tests.csproj"),
                   "--no-restore", "--configuration", "Release", "--filter",
                   "FullyQualifiedName=SlateWindows.Tests.Censuses.A11yTriggerParityCensus.SourceInventoryCanBeExportedForTheLedgerGenerator"]
        run = subprocess.run(command, cwd=REPO, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                             encoding="utf-8", errors="replace", check=False)
        if run.returncode:
            raise SystemExit(run.stdout)
        return json.loads(output.read_text(encoding="utf-8"))


def site_id(site: dict) -> str:
    return f"{site['Member']}@{site['Ordinal']}"


def cell(sites: list[dict]) -> str:
    return "; ".join(f"`{site_id(site)}`" for site in sorted(sites, key=site_id)) or "—"


def render(data: dict, config: dict) -> str:
    keys = data["Keys"]
    # Drift is a failure of --check and --write alike, so these are explicit
    # exits: a bare assert disappears under `python -O` and would let a stale
    # designated set render as "ledger current".
    if len(keys) != len(set(keys)):
        raise SystemExit("duplicate binding keys")
    residue = {}
    for side in ("Windows", "Mac"):
        present = {site["Key"] for site in data[side]}
        missing = set(keys) - present
        if missing != set(config["designated"][side]):
            raise SystemExit(f"{side}: designation drift {sorted(missing ^ set(config['designated'][side]))}")
        residue[side] = {site_id(site) for site in data[side] if site["Key"] == "HostComposed"}
        if residue[side] != set(config["residue"][side]):
            raise SystemExit(f"{side}: residue drift {sorted(residue[side] ^ set(config['residue'][side]))}")
    lines = [BEGIN, "", "## Whole-corpus trigger ledger (D-7)", "",
             "Generated by `scripts/a11y_trigger_ledger.py`. `@N` identifies each construction",
             "of that key inside the member; no sites are elided. C# sites bind to the",
             "generated event type. Swift sites use the recorded #1108 lexical boundary.",
             "The unit-observed column proves dispatcher arguments for each corpus event;",
             "it does not claim that every listed user trigger or AT listening route was run.",
             "Canvas and Graph retain their separate structural-key and journey censuses.", "",
             "| Key | Role | Mac site(s) | Windows site(s) | Windows fact(s) | Observed by | Designation |",
             "|---|---|---|---|---|---|---|"]
    for key in keys:
        if key in FAMILIES:
            doc, fact = FAMILIES[key]
            lines.append(f"| `{key}` | family-ref | [{key} ledger]({doc}) | [{key} ledger]({doc}) | `Censuses/{fact}` | Existing family ledger | Folded by reference; no duplicate family rows |")
            continue
        role = config["roles"].get(key, "posted")
        mac = cell([site for site in data["Mac"] if site["Key"] == key])
        windows = cell([site for site in data["Windows"] if site["Key"] == key])
        notes = []
        for side in ("Mac", "Windows"):
            if key in config["designated"][side]:
                entry = config["designated"][side][key]
                notes.append(f"{side} {entry['status']}: {entry['reason']} [{Path(entry['decision']).stem}](../../{entry['decision']})")
        lines.append(f"| `{key}` | {role} | {mac} | {windows} | `{CORPUS_FACT}` | unit-observed: `{DISPATCH_FACT}` | {'; '.join(notes) or '—'} |")
    lines += ["", "## Host-composed residue register (D-8)", "",
              "Every row names one construction and its producing engine. These are",
              "explicit scope decisions; a new or removed site fails the census. Marker",
              "counts differ from construction counts because one family marker can cover",
              f"several sites. The binding-aware inventory found {len(residue['Windows'])} Windows constructions",
              "after scan conversion (the earlier unqualified-spelling scan missed one),",
              f"and {len(residue['Mac'])} Mac constructions. Each site's decision status is recorded below.", "",
              "| Platform | Site | Engine | Decision source | Status |",
              "|---|---|---|---|---|"]
    for side in ("Windows", "Mac"):
        for site, row in sorted(config["residue"][side].items()):
            lines.append(f"| {side} | `{site}` | {row['engine']} | [{Path(row['decision']).stem}](../../{row['decision']}) | {row['status']} |")
    return "\n".join(lines + ["", END])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--inventory", type=Path)
    args = parser.parse_args()
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    data = json.loads(args.inventory.read_text(encoding="utf-8")) if args.inventory else inventory()
    generated = render(data, config)
    original = DOCUMENT.read_bytes().decode("utf-8")
    newline = "\r\n" if "\r\n" in original else "\n"
    normalized = original.replace("\r\n", "\n")
    if BEGIN in normalized:
        start, finish = normalized.index(BEGIN), normalized.index(END) + len(END)
        updated = normalized[:start] + generated + normalized[finish:]
    else:
        updated = normalized.rstrip() + "\n\n" + generated + "\n"
    if args.check:
        if normalized != updated:
            raise SystemExit("A11y trigger ledger is stale; regenerate with --write.")
        print(f"A11y ledger current: {len(data['Keys'])} top-level keys.")
    elif args.write:
        DOCUMENT.write_bytes(updated.replace("\n", newline).encode("utf-8"))
    else:
        print(generated)


if __name__ == "__main__":
    main()
